### ISSUE TITLE
[v2] Rendering <pre class="language-"></pre> as code block

### ISSUE THREAD

**Issue by dio** [mdx-js/mdx#1332]
### Rendering `<pre class=""></pre>` as code block

To render `<pre class=""></pre>` as code block, this is useful for example to embed code block in a markdown table:

```
| Metric Name | Labels | PromQL Expression |
|---|---|---|
| `grpc_server_handled_total` |  `component` `grpc_code` `grpc_method` `grpc_type`  | <pre class="language-text">sum(rate(grpc_server_handled_total{component="tsb", grpc_code!="OK", grpc_type="unary", grpc_method!="SendAuditLog"}[1m])) by (grpc_code)</pre> |
```

as you can see GitHub renders the above as code block 👇 

| Metric Name | Labels | PromQL Expression |
|---|---|---|
| `grpc_server_handled_total` |  `component` `grpc_code` `grpc_method` `grpc_type`  | <pre class="language-text">sum(rate(grpc_server_handled_total{component="tsb", grpc_code!="OK", grpc_type="unary", grpc_method!="SendAuditLog"}[1m])) by (grpc_code)</pre> |
### Problem

Currently using `<pre />` docusaurus render it as a plain text.

### Expected behavior

Render `<pre />` as a code block, and has a "Copy" button too.

**Comment by ChristianMurphy** [comment]
> as you can see GitHub renders the above as code block

GitHub doesn't render it as a code block.
It renders it as a `<pre>` tag.
The GitHub stylesheet adds a background and border radius, something which you could add to your stylesheet as well.

---

More generally `pre` != a codeblock, it is any preformatted text.
It makes more sense to keep highlighting as an extension/plugin.
Which is documented at https://mdxjs.com/guides/syntax-highlighting

---

If you have specific questions on how to implement this, feel free to reach out on the discussions/support board https://github.com/mdx-js/mdx/discussions

**Comment by dio** [comment]
@ChristianMurphy thanks. I tried to get around this using:

```
<CodeBlock>{`sum(rate(grpc_client_msg_received_total{component="tsbd", grpc_type="server_stream"}[30s])) by (cluster_name)`}</CodeBlock>
```

But I got:

```
TypeError: children.replace is not a function
(undefined) TypeError: children.replace is not a function
    at module.exports.__webpack_exports__.a (main:12393:19)
    at d (main:35913:498)
    at $a (main:35916:16)
    at a.b.render (main:35921:476)
    at a.b.read (main:35921:18)
    at Object.renderToString (main:35931:364)
    at serverEntry_render (main:52829:395)
Error: Failed to compile with errors.
    at compiler.run (/home/ubuntu/my-website/node_modules/@docusaurus/core/lib/webpack/utils.js:164:24)
    at finalCallback (/home/ubuntu/my-website/node_modules/webpack/lib/MultiCompiler.js:254:12)
    at runWithDependencies.err (/home/ubuntu/my-website/node_modules/webpack/lib/MultiCompiler.js:277:6)
    at done (/home/ubuntu/my-website/node_modules/neo-async/async.js:2931:13)
    at runCompilers (/home/ubuntu/my-website/node_modules/webpack/lib/MultiCompiler.js:181:48)
    at err (/home/ubuntu/my-website/node_modules/webpack/lib/MultiCompiler.js:188:7)
    at compiler.run (/home/ubuntu/my-website/node_modules/webpack/lib/MultiCompiler.js:270:7)
    at finalCallback (/home/ubuntu/my-website/node_modules/webpack/lib/Compiler.js:257:39)
    at hooks.done.callAsync.err (/home/ubuntu/my-website/node_modules/webpack/lib/Compiler.js:273:13)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/home/ubuntu/my-website/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:42:1)
    at AsyncSeriesHook.lazyCompileHook (/home/ubuntu/my-website/node_modules/tapable/lib/Hook.js:154:20)
    at onCompiled (/home/ubuntu/my-website/node_modules/webpack/lib/Compiler.js:271:21)
    at hooks.afterCompile.callAsync.err (/home/ubuntu/my-website/node_modules/webpack/lib/Compiler.js:681:15)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/home/ubuntu/my-website/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (/home/ubuntu/my-website/node_modules/tapable/lib/Hook.js:154:20)
    at compilation.seal.err (/home/ubuntu/my-website/node_modules/webpack/lib/Compiler.js:678:31)
```

Do you know why? Thanks!

**Comment by dio** [comment]
This is the repro: https://github.com/dio/bracket-mystery

**Comment by ChristianMurphy** [comment]
@dio I'd be happy to help, could we move this to a thread in https://github.com/mdx-js/mdx/discussions ?
