### ISSUE TITLE
Escaping of double quotes in JSX attribute leads to esbuild incompatibility

### ISSUE THREAD

**Issue by aleclarson** [mdx-js/mdx#1513]
### Subject of the issue

JSON in a JSX attribute has its double quotes escaped, which leads to `esbuild` choking on it.

```mdx
<Foo bar='{ "a": 1 }' />
```
..becomes..
```tsx
/* @jsxRuntime classic */
/* @jsx mdx */
/* @jsxFrag mdx.Fragment */
const MDXLayout = "wrapper";
function MDXContent({components, ...props}) {
  return <MDXLayout components={components} {...props}><Foo bar="{ \"a\": 1 }" mdxType="Foo" /></MDXLayout>;
}
MDXContent.isMDXComponent = true;
export default MDXContent;
```
..with the important part being:
```js
bar="{ \"a\": 1 }" 
```
..which translates to this JavaScript string:
```js
'bar="{ \\"a\\": 1 }"'
```
The escaped forward slashes seem to be causing `esbuild` to think the JSX attribute ends before the `a` key in the JSON string.

### Your environment

*   **OS**: N/A
*   **Packages**: `@mdx-js/mdx@next` (See the reproduction for others)
*   **Env**: N/A

### Steps to reproduce

Follow the steps on this repo:  
https://github.com/aleclarson/repro/tree/mdxjs-1#readme

### Expected behaviour

Switch back to doing `&quot;` if possible. Or stop escaping the escapes.

### Actual behaviour

```
❯ yarn vite build
yarn run v1.22.10
warning package.json: No license field
$ ~/vite-plugin-mdx/examples/react/node_modules/.bin/vite build
vite v2.1.5 building for production...
transforming (3) src/index.jsx
mdx => '/* @jsxRuntime classic */\n' +
  '/* @jsx mdx */\n' +
  '/* @jsxFrag mdx.Fragment */\n' +
  'const makeShortcode = name => props => {\n' +
  '  console.warn("Component `%s` was not imported, exported, or provided by MDXProvider as global scope", name);\n' +
  '  return <>{props.children}</>;\n' +
  '};\n' +
  'const Count = makeShortcode("Count");\n' +
  "import {Counter} from './Counter.jsx';\n" +
  'const MDXLayout = "wrapper";\n' +
  'function MDXContent({components, ...props}) {\n' +
  '  return <MDXLayout components={components} {...props}><h1>{"Hello"}</h1><Count json="{\\"a\\":\\"b\\"}" mdxType="Count" /></MDXLayout>;\n' +
  '}\n' +
  'MDXContent.isMDXComponent = true;\n' +
  'export default MDXContent;\n'
✓ 8 modules transformed.
[vite-plugin-mdx] Transform failed with 1 error:
<stdin>:12:90: error: Expected ">" but found "\\"
file: ~/vite-plugin-mdx/examples/react/src/Hello.mdx
error during build:
Error: Transform failed with 1 error:
<stdin>:12:90: error: Expected ">" but found "\\"
    at failureErrorWithLog (~/vite-plugin-mdx/examples/react/node_modules/esbuild/lib/main.js:1145:15)
    at ~/vite-plugin-mdx/examples/react/node_modules/esbuild/lib/main.js:1026:33
    at ~/vite-plugin-mdx/examples/react/node_modules/esbuild/lib/main.js:550:9
    at handleIncomingPacket (~/vite-plugin-mdx/examples/react/node_modules/esbuild/lib/main.js:639:9)
    at Socket.readFromStdout (~/vite-plugin-mdx/examples/react/node_modules/esbuild/lib/main.js:517:7)
    at Socket.emit (node:events:378:20)
    at addChunk (node:internal/streams/readable:313:12)
    at readableAddChunk (node:internal/streams/readable:288:9)
    at Socket.Readable.push (node:internal/streams/readable:227:10)
    at Pipe.onStreamRead (node:internal/stream_base_commons:190:23)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by aleclarson** [comment]
Hmm, on second thought, this might be an `esbuild` bug :)

**Comment by wooorm** [comment]
This is a bug here: https://github.com/mdx-js/mdx/blob/5169bf1f5d7b730b6f20a5eecee0b9ea0d977e56/packages/mdx/estree-to-js.js#L140-L147

It would be solved upstream when this PR lands: https://github.com/davidbonnet/astring/pull/480/files#diff-48d731d988c1539f085b428de2166d696b64ab21eabe0b3273492ee90232457cR1121-R1128 (and the above code can be removed)

It is *also* a bug that esbuild crashes.

**Comment by aleclarson** [comment]
> It is _also_ a bug that esbuild crashes.

It appears not: https://github.com/evanw/esbuild/issues/1115#issuecomment-814020230

**Comment by wooorm** [comment]
Finally fixed in the last RC! See https://v2.mdxjs.com for more info on that. Please try it out, read through the docs, and let us know what’s missing or undocumented or broken!
