### ISSUE TITLE
Client side error with getStaticProps/getServerSideProps/getStaticPaths with nodejs module (e.g. fs or path)

### ISSUE THREAD

**Issue by mizozobu** [mdx-js/mdx#1909]
### Initial checklist

- [X] I read the [support docs](https://mdxjs.com/community/support/)
- [X] I read the [contributing guide](https://mdxjs.com/community/contribute/)
- [X] I agree to follow the [code of conduct](https://github.com/mdx-js/.github/blob/HEAD/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Amdx-js&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

@mdx-js/loader@1.5.1", @mdx-js/react@1.6.18

### Steps to reproduce

1. Create a nextjs app with the template.

    ```sh
    yarn create next-app --example with-mdx with-mdx-app
    ```

1.  Add a mdx page with nodejs module (e.g. `path`).

    `pages/mdx.mdx`
    ```js
    import { join } from 'path';
    
    export const getStaticProps = async (context) => {
      console.log(join('a', 'b'));
      return {
        props: {},
      };
    };
    
    # mdx
    ```

1. Render it on the browser.

### Expected behavior

MDX pages should work with `getStaticProps`, `getServerSideProps`, and `getStaticPaths` with nodejs module because nextjs pages do work with them.

`pages/jsx.jsx`
```js
import { join } from 'path';

export const getStaticProps = async (context) => {
  console.log(join('a', 'b'));
  return {
    props: {},
  };
};

const _IndexPage = () => <h1>jsx</h1>;

export default _IndexPage;
```

### Actual behavior

There are some errors on client side (no errors on server side). This is what I get on the browser console.

```
Warning: Expected server HTML to contain a matching <wrapper> in <div>.
    at wrapper
    at MDXContent (webpack-internal:///./pages/mdx.mdx:128:29)
    at App (webpack-internal:///./node_modules/next/dist/pages/_app.js:178:9)
    at ErrorBoundary (webpack-internal:///./node_modules/next/dist/compiled/@next/react-dev-overlay/client.js:8:20584)
    at ReactDevOverlay (webpack-internal:///./node_modules/next/dist/compiled/@next/react-dev-overlay/client.js:8:23125)
    at Container (webpack-internal:///./node_modules/next/dist/client/index.js:332:9)
    at AppContainer (webpack-internal:///./node_modules/next/dist/client/index.js:766:26)
    at Root (webpack-internal:///./node_modules/next/dist/client/index.js:883:27)
Warning: The tag <wrapper> is unrecognized in this browser. If you meant to render a React component, start its name with an uppercase letter.
    at wrapper
    at MDXContent (webpack-internal:///./pages/mdx.mdx:128:29)
    at App (webpack-internal:///./node_modules/next/dist/pages/_app.js:178:9)
    at ErrorBoundary (webpack-internal:///./node_modules/next/dist/compiled/@next/react-dev-overlay/client.js:8:20584)
    at ReactDevOverlay (webpack-internal:///./node_modules/next/dist/compiled/@next/react-dev-overlay/client.js:8:23125)
    at Container (webpack-internal:///./node_modules/next/dist/client/index.js:332:9)
    at AppContainer (webpack-internal:///./node_modules/next/dist/client/index.js:766:26)
    at Root (webpack-internal:///./node_modules/next/dist/client/index.js:883:27)
Warning: React does not recognize the `getServerSideProps` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `getserversideprops` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
    at wrapper
    at MDXContent (webpack-internal:///./pages/mdx.mdx:128:29)
    at App (webpack-internal:///./node_modules/next/dist/pages/_app.js:178:9)
    at ErrorBoundary (webpack-internal:///./node_modules/next/dist/compiled/@next/react-dev-overlay/client.js:8:20584)
    at ReactDevOverlay (webpack-internal:///./node_modules/next/dist/compiled/@next/react-dev-overlay/client.js:8:23125)
    at Container (webpack-internal:///./node_modules/next/dist/client/index.js:332:9)
    at AppContainer (webpack-internal:///./node_modules/next/dist/client/index.js:766:26)
    at Root (webpack-internal:///./node_modules/next/dist/client/index.js:883:27)
Warning: React does not recognize the `mdxType` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `mdxtype` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
    at wrapper
    at MDXContent (webpack-internal:///./pages/mdx.mdx:128:29)
    at App (webpack-internal:///./node_modules/next/dist/pages/_app.js:178:9)
    at ErrorBoundary (webpack-internal:///./node_modules/next/dist/compiled/@next/react-dev-overlay/client.js:8:20584)
    at ReactDevOverlay (webpack-internal:///./node_modules/next/dist/compiled/@next/react-dev-overlay/client.js:8:23125)
    at Container (webpack-internal:///./node_modules/next/dist/client/index.js:332:9)
    at AppContainer (webpack-internal:///./node_modules/next/dist/client/index.js:766:26)
    at Root (webpack-internal:///./node_modules/next/dist/client/index.js:883:27)
```

With these errors, `MDXProvider` from `@mdx-js/react` does not work properly (and probably more issues follow).

### Runtime

Node v16

### Package manager

yarn v1

### OS

macOS

### Build and bundle tools

Next.js

**Comment by wooorm** [comment]
Use v2, it likely solves it

**Comment by mizozobu** [comment]
@wooorm
Upgrading `@mdx-js/loader` and `@mdx-js/react` to `2.0.0-rc.2` does solve this issue. Maybe it's time to upgrade. Appreciate your great work.
