### ISSUE TITLE
date mismatch between client and server

### ISSUE THREAD

**Issue by jdevries3133** [mdx-js/mdx#2041]
### Initial checklist

- [X] I read the [support docs](https://mdxjs.com/community/support/)
- [X] I read the [contributing guide](https://mdxjs.com/community/contribute/)
- [X] I agree to follow the [code of conduct](https://github.com/mdx-js/.github/blob/HEAD/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Amdx-js&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

^2.1.1

### Link to runnable example

https://codesandbox.io/s/nostalgic-burnell-zbru8o?file=/app/routes/index.jsx

### Steps to reproduce

See runnable example.

### Expected behavior

The date should be the same from the client to the server.

### Actual behavior

The date does not match between client and server, producing a warning:

```
Warning: Text content did not match. Server: "Sat May 14 2022 00:00:00 GMT+0000 (Coordinated Universal Time)" Client: "Fri May 13 2022 20:00:00 GMT-0400 (Eastern Daylight Time)"
    at p
    at Index
    at RemixRoute (https://zbru8o.sse.codesandbox.io/build/_shared/chunk-ZRZJX565.js:2893:3)
    at Outlet2 (https://zbru8o.sse.codesandbox.io/build/_shared/chunk-ZRZJX565.js:445:14)
    at body
    at html
    at Document (https://zbru8o.sse.codesandbox.io/build/root-Z6SWTN4Y.js:30:20)
    at App (https://zbru8o.sse.codesandbox.io/build/root-Z6SWTN4Y.js:42:14)
    at RemixCatchBoundary (https://zbru8o.sse.codesandbox.io/build/_shared/chunk-ZRZJX565.js:1464:10)
    at RemixErrorBoundary (https://zbru8o.sse.codesandbox.io/build/_shared/chunk-ZRZJX565.js:1403:5)
    at RemixRoute (https://zbru8o.sse.codesandbox.io/build/_shared/chunk-ZRZJX565.js:2893:3)
    at Routes (https://zbru8o.sse.codesandbox.io/build/_shared/chunk-ZRZJX565.js:2876:7)
    at Router2 (https://zbru8o.sse.codesandbox.io/build/_shared/chunk-ZRZJX565.js:452:19)
    at RemixCatchBoundary (https://zbru8o.sse.codesandbox.io/build/_shared/chunk-ZRZJX565.js:1464:10)
    at RemixErrorBoundary (https://zbru8o.sse.codesandbox.io/build/_shared/chunk-ZRZJX565.js:1403:5)
    at RemixEntry (https://zbru8o.sse.codesandbox.io/build/_shared/chunk-ZRZJX565.js:2773:12)
    at RemixBrowser (https://zbru8o.sse.codesandbox.io/build/_shared/chunk-ZRZJX565.js:3171:42)
```

I have a feeling I'm missing some code in my app to handle timezones, but I'm not sure.

### Runtime

Node v16

### Package manager

yarn v1

### OS

macOS

### Build and bundle tools

Remix

**Comment by wooorm** [comment]
Hi. This has nothing to do with MDX. It has to do with React, and/or JavaScript.
You can search “react hydration error mismatch” and similar on Google to head for a solution.

**Comment by jdevries3133** [comment]
> react hydration error mismatch



> Hi. This has nothing to do with MDX. It has to do with React, and/or JavaScript. You can search “react hydration error mismatch” and similar on Google to head for a solution.

Well, MDX is parsing the date from the mdx attributes, and it's doing it differently on the client versus the server, which is the cause of the content mismatch, so in that sense, it does have to do with MDX. I'm wondering why the MDX yaml parser produces different dates on the client versus the server. Again, I feel like it might be a timezone issue, where the browser uses local time and the server uses GMT or something like that.

For context, my local timezone is EST (UTC−05:00)

**Comment by wooorm** [comment]
Again, this has nothing to do with MDX.

This is how JavaScript works: it normalized dates to the environment. Your users will be at a different time than your server.
