### ISSUE TITLE
Curl / tar command line requirement does not work in Windows

### ISSUE THREAD

**Issue by Ciantic** [mdx-js/mdx#248]
Even though I have curl.exe and tar.exe in the PATH (they are provided by Windows 10 these days in dev mode) the installation fails:

```
PS C:\Source\Blog> npm init mdx
npx: installed 15 in 8.216s
t a r%:  TEortraolr   o pe n%i nRge caericvheidv e%:  XFfaeirlde d  Atvoe roapgeen  S'p\e\e.d\ t a pTei0m'e
    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  2740    0  2740    0     0   2740      0 --:--:--  0:00:01 --:--:--  2192
curl: (23) Failed writing body (1356 != 1370)
{ Error: Command failed: curl https://codeload.github.com/mdx-js/mdx/tar.gz/master | tar -xz -C next-mdx --strip=3 mdx-master/examples/next
    at checkExecSyncError (child_process.js:600:11)
    at execSync (child_process.js:637:13)
    at getTar (\npm-cache\_npx\13628\node_modules\create-mdx\node_modules\initit\index.js:37:3)
    at create (\npm-cache\_npx\13628\node_modules\create-mdx\node_modules\initit\index.js:57:3)
    at Object.<anonymous> (\npm-cache\_npx\13628\node_modules\create-mdx\cli.js:7:1)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 32140,
  stdout: null,
  stderr: null }
```

I suspect it can't still use curl and tar with Windows.

**Comment by johno** [comment]
I'm going to go ahead and close this since it's an upstream issue. Hopefully we can get this resolved up there sometime soon.
