### ISSUE TITLE
[Webpack Loader] Error with 'function' in loaders file

### ISSUE THREAD

**Issue by kilmc** [mdx-js/mdx#272]
Hi folks,

I seem to be having trouble getting things setup. I'm attempting to use mdx with a basic webpack config but I've been getting this error when I try to even import a `.md` file.

```ERROR in ./src/doc.md
Module build failed (from ./node_modules/@mdx-js/loader/index.js):
/Users/kilianmcmahon/Sites/experiments/mdx/node_modules/@mdx-js/loader/index.js:4
module.exports = async function(content) {
                       ^^^^^^^^

SyntaxError: Unexpected token function
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at loadLoader (/Users/kilianmcmahon/Sites/experiments/mdx/node_modules/loader-runner/lib/loadLoader.js:13:17)
 @ ./src/Site.js 4:0-27
 @ ./src/index.js
 @ multi (webpack)-dev-server/client?http://localhost:8080 ./src
ℹ ｢wdm｣: Failed to compile.
```

My webpack config is 
```
const path = require('path');
module.exports = {
  output: {
    path: path.resolve(__dirname, 'dist'),
    filename: 'main.js',
    publicPath: '/'
  },
  devServer: {
    contentBase: './dist'
  },
  mode: 'development',
  resolve: {
    extensions: ['*', '.js', '.jsx']
  },
  module: {
    rules: [
      {
        test: /\.(js|jsx)$/,
        exclude: /node_modules/,
        use: ['babel-loader']
      },
      {
        test: /.mdx?$/,
        use: ['babel-loader', '@mdx-js/loader']
      }
    ]
  }
};
```

Curious if this is just my having messed up the setup or if it's a bug. Any help would be super appreciated. Thanks.

**Comment by timneutkens** [comment]
Sounds like you're on a version of Node.js below 7.5, can you try running `node -v`
