### ISSUE TITLE
MDX errors when using webpack loader happen out-of-band

### ISSUE THREAD

**Issue by timneutkens** [mdx-js/mdx#347]
### MDX errors when using webpack loader happen out-of-band

Describe your issue here.  Remember, this is _not_ a place to ask questions.  For that, go to [spectrum](https://spectrum.chat/mdx)

### Your environment

*   MacOS
*   webpack + mdx-loader

### Steps to reproduce

For some reason when an error is thrown it ends up being unhandled and isn't passed back to webpack, meaning webpack won't show which files actually broke.

### Expected behaviour

I'm not entirely sure what happens because we do try/catch the mdx() function.

### Actual behaviour

What happens instead?

Here's the stacktrace:

```
(node:8222) UnhandledPromiseRejectionWarning: Error: MDX doesn't support using "default" as a named export, use "export default" statement instead.

For example, instead of:

export { Layout as default }

use:

export default Layout
    at toJSX (/home/circleci/repo/node_modules/@mdx-js/mdx/mdx-hast-to-jsx.js:75:17)
    at Compiler.tree (/home/circleci/repo/node_modules/@mdx-js/mdx/mdx-hast-to-jsx.js:155:12)
    at Function.stringify (/home/circleci/repo/node_modules/unified/index.js:351:12)
    at pipelineStringify (/home/circleci/repo/node_modules/unified/index.js:42:25)
    at wrapped (/home/circleci/repo/node_modules/trough/wrap.js:25:19)
    at next (/home/circleci/repo/node_modules/trough/index.js:58:24)
    at done (/home/circleci/repo/node_modules/trough/wrap.js:56:16)
    at done (/home/circleci/repo/node_modules/unified/index.js:36:7)
    at done (/home/circleci/repo/node_modules/unified/index.js:310:11)
    at next (/home/circleci/repo/node_modules/trough/index.js:60:14)
    at done (/home/circleci/repo/node_modules/trough/wrap.js:56:16)
    at then (/home/circleci/repo/node_modules/trough/wrap.js:63:5)
    at wrapped (/home/circleci/repo/node_modules/trough/wrap.js:46:9)
    at next (/home/circleci/repo/node_modules/trough/index.js:58:24)
    at done (/home/circleci/repo/node_modules/trough/wrap.js:56:16)
    at then (/home/circleci/repo/node_modules/trough/wrap.js:63:5)
(node:8222) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:8222) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:8222) UnhandledPromiseRejectionWarning: Error: MDX doesn't support using "default" as a named export, use "export default" statement instead.
```

I'll add a reproduction if @johno @wooorm @silvenon don't know what's going on either.

**Comment by johno** [comment]
Yeah, I think this _might_ be because we aren't properly using the webpack error API. I can dig into that a little later today to see if that's it. If it is, should be a p quick fix.

**Comment by johno** [comment]
Nvm, we are. No idea why that error isn't being caught. 🤔

**Comment by timneutkens** [comment]
@johno I solved this by changing next-mdx to no longer force a specific mdx-js/loader version. It was on an older version.
