### ISSUE TITLE
npm init mdx gatsby throws error

### ISSUE THREAD

**Issue by detj** [mdx-js/mdx#383]
### Subject of the issue

Running `npm init mdx gatsby` as per the [docs](https://mdxjs.com/getting-started/#projects-libraries-and-frameworks) throws the following error

```
npx: installed 15 in 5.388s
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  431k    0  431k    0     0   208k      0 --:--:--  0:00:02 --:--:--  208k
tar: mdx-master/examples/gatsby: Not found in archive
tar: Error exit delayed from previous errors.
{ Error: Command failed: curl https://codeload.github.com/mdx-js/mdx/tar.gz/master | tar -xz -C gatsby-mdx --strip=3 mdx-master/examples/gatsby
    at checkExecSyncError (child_process.js:616:11)
    at execSync (child_process.js:653:13)
    at getTar (/Users/detj/.npm/_npx/48363/lib/node_modules/create-mdx/node_modules/initit/index.js:37:3)
    at create (/Users/detj/.npm/_npx/48363/lib/node_modules/create-mdx/node_modules/initit/index.js:57:3)
    at Object.<anonymous> (/Users/detj/.npm/_npx/48363/lib/node_modules/create-mdx/cli.js:8:1)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 48369,
  stdout: null,
  stderr: null }
```

### Your environment

* macOS 10.14
* node 10.15.0
* npm 6.7.0

### Steps to reproduce

Run the following command
```
$ npm init mdx gatsby
```

### Expected behaviour
I was trying the installation procedure as per the docs. I suppose it should setup a directory using a Gatsby starter thats using mdx.

### Actual behaviour

Threw an error

**Comment by johno** [comment]
Thanks for reporting this, it should now be fixed 👍.
