### ISSUE TITLE
<MDXTag error

### ISSUE THREAD

**Issue by gurpreet-hanjra** [mdx-js/mdx#434]
### Subject of the issue

I'm trying to use mdx using custom webpack configuration. After adding dependencies and loaders, I get this error -

ERROR in ./src/scripts/components/login/test.mdx
Module build failed (from ./node_modules/babel-loader/lib/index.js):
SyntaxError: /Users/gurpreetsinghhanjra/Desktop/projects/official/frontend/src/scripts/components/login/test.mdx: Unexpected token (17:11)

  15 |     const { components, ...props } = this.props
  16 | 
> 17 |     return <MDXTag
     |            ^
  18 |              name="wrapper"
  19 |              
  20 |              components={components}><MDXTag name="h1" components={components}>{`Hello, world!`}</MDXTag>
    at Parser.raise (/Users/gurpreetsinghhanjra/Desktop/projects/official/frontend/node_modules/@babel/parser/lib/index.js:3831:17)
    at Parser.unexpected (/Users/gurpreetsinghhanjra/Desktop/projects/official/frontend/node_modules/@babel/parser/lib/index.js:5143:16)
    at Parser.parseExprAtom (/Users/gurpreetsinghhanjra/Desktop/projects/official/frontend/node_modules/@babel/parser/lib/index.js:6283:20)
    at Parser.parseExprSubscripts (/Users/gurpreetsinghhanjra/Desktop/projects/official/frontend/node_modules/@babel/parser/lib/index.js:5862:23)
    at Parser.parseMaybeUnary (/Users/gurpreetsinghhanjra/Desktop/projects/official/frontend/node_modules/@babel/parser/lib/index.js:5842:21)
    at Parser.parseExprOps (/Users/gurpreetsinghhanjra/Desktop/projects/official/frontend/node_modules/@babel/parser/lib/index.js:5729:23)
    at Parser.parseMaybeConditional (/Users/gurpreetsinghhanjra/Desktop/projects/official/frontend/node_modules/@babel/parser/lib/index.js:5702:23)
    at Parser.parseMaybeAssign (/Users/gurpreetsinghhanjra/Desktop/projects/official/frontend/node_modules/@babel/parser/lib/index.js:5647:21)
    at Parser.parseExpression (/Users/gurpreetsinghhanjra/Desktop/projects/official/frontend/node_modules/@babel/parser/lib/index.js:5595:23)
    at Parser.parseReturnStatement (/Users/gurpreetsinghhanjra/Desktop/projects/official/frontend/node_modules/@babel/parser/lib/index.js:7614:28)
    at Parser.parseStatementContent (/Users/gurpreetsinghhanjra/Desktop/projects/official/frontend/node_modules/@babel/parser/lib/index.js:7292:21)
    at Parser.parseStatement (/Users/gurpreetsinghhanjra/Desktop/projects/official/frontend/node_modules/@babel/parser/lib/index.js:7248:17)
    at Parser.parseBlockOrModuleBlockBody (/Users/gurpreetsinghhanjra/Desktop/projects/official/frontend/node_modules/@babel/parser/lib/index.js:7812:25)
    at Parser.parseBlockBody (/Users/gurpreetsinghhanjra/Desktop/projects/official/frontend/node_modules/@babel/parser/lib/index.js:7799:10)
    at Parser.parseBlock (/Users/gurpreetsinghhanjra/Desktop/projects/official/frontend/node_modules/@babel/parser/lib/index.js:7788:10)
    at Parser.parseFunctionBody (/Users/gurpreetsinghhanjra/Desktop/projects/official/frontend/node_modules/@babel/parser/lib/index.js:6876:24)
### Your environment

*   Name and version of operating system
*   Names and version of required packages
*   Version of node, npm, yarn, or names and versions of browser

### Steps to reproduce

Tell us how to reproduce this issue.  Please provide a working and simplified example.

🎉 BONUS POINTS for creating a [minimal reproduction](https://stackoverflow.com/help/mcve) and uploading it to GitHub.  This will get you the fastest support.  🎉

### Expected behaviour

Should render correctly

### Actual behaviour

Throws an [error]([url](`url`))

**Comment by johno** [comment]
Can you post your babel and webpack configs or create a minimal reproduction? It first glance it looks like the JSX (what MDX transpiles to) isn't being handled properly.

**Comment by johno** [comment]
I'm going to go ahead and close this due to lack of response. Please feel free to open up a new issue if you'd like to include more details so we can help get your issue resolved!

**Comment by leifriksheim** [comment]
I also get this error in my custom Webpack setup.

My dependencies:

```
"devDependencies": {
    "@babel/cli": "^7.2.3",
    "@babel/core": "^7.4.0",
    "@babel/plugin-proposal-object-rest-spread": "^7.4.0",
    "@babel/preset-env": "^7.4.1",
    "@babel/preset-react": "^7.0.0",
    "@mdx-js/loader": "^0.20.3",
    "babel-loader": "^8.0.5",
    "css-loader": "^1.0.0",
    "html-webpack-plugin": "^3.2.0",
    "style-loader": "^0.23.0",
    "webpack": "^4.19.1",
    "webpack-cli": "^3.1.1",
    "webpack-dev-server": "^3.1.8"
  },
  "dependencies": {
    "@babel/polyfill": "^7.4.0",
    "react": "^16.5.2",
    "react-dom": "^16.5.2"
  }
```
